name: Deploying hardhat contract
'on':
  pull_request:
      branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3
      
     # Install dependencies
    - name: Install Dependencies
      run: yarn install
      continue-on-error: false
  

    - run: yarn --ignore-scripts
      shell: bash
    - name: Create local node and deploy
      run: |
        yarn hardhat node &
        yarn hardhat run scripts/deploy.js --network localhost
    - name: Run Tests
      run: yarn hardhat test

        
    # Merge to main branch
    - name: Merge to Main
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main' # Only merge on successful push to main branch
      run: git merge origin/main --no-edit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false
    
#     Slither test
    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      id: slither
      with:
        sarif: results.sarif
        fail-on: none

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
